# Generated by Django 3.0.4 on 2020-03-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='input_meta_data',
        ),
    ]
